# Generated by Django 5.1.1 on 2024-10-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondb', '0002_rename_mymodel_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default='item', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='collection',
            field=models.CharField(default='twilight_masquerade', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='element_type',
            field=models.CharField(default='trainer', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.CharField(default='images/1-Venusaur-ex-Stellar-Crown.png', max_length=128),
        ),
        migrations.AddField(
            model_name='card',
            name='stage',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='suffix',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default='bulbasaur', max_length=100),
        ),
    ]
