# Generated by Django 5.1.1 on 2024-10-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondb', '0003_remove_card_description_card_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
    ]
