# Generated by Django 5.1.1 on 2024-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondb', '0005_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.CharField(default='images/1-Venusaur-ex-Stellar-Crown.png', max_length=128),
        ),
    ]
