# Generated by Django 4.2.16 on 2024-11-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondb', '0006_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='set_id',
            field=models.CharField(default='sv7', max_length=30),
        ),
    ]
