# Generated by Django 5.1.1 on 2024-11-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpokemon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userPokemon',
        ),
    ]
