# Generated by Django 5.1.1 on 2024-11-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpokemon',
            name='numberOfPokemon',
        ),
    ]
