# Generated by Django 5.1.1 on 2024-11-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userpokemon_numberofpokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='listPokemon',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
