# Generated by Django 5.1.1 on 2024-11-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_listpokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpokemon',
            name='listPokemon',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
