# Generated by Django 4.2.16 on 2024-11-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userpokemon_listpokemon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userPokemon',
        ),
    ]