# Generated by Django 5.1.1 on 2024-11-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userpokemon_listpokemon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userPokemon',
        ),
    ]
