# Generated by Django 5.1.1 on 2024-11-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_cards',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='api_cards',
            name='pokemon_id',
        ),
        migrations.AlterField(
            model_name='api_cards',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
