# Generated by Django 5.1.1 on 2024-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_api', '0002_remove_api_cards_isbn_remove_api_cards_pokemon_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_cards',
            name='rarity',
            field=models.CharField(default='normal', max_length=255),
        ),
    ]
